package cz.csas.datastructures.patrol.model

import java.util.UUID

/** A single stop on the patrol route. The id is always generated by the server. */
data class Checkpoint(
    val id: UUID,
    val name: String,
    val description: String,
    val priority: Priority,
)
